### ISSUE TITLE
Plugin not running

### ISSUE THREAD

**Issue by MoneyRBK** [ShermansWorld/AlathraWar#11]
When I put this plugin in my server's plugin folder, it doesn't respond or run in any way after a server restart. I have all the plugins in which it is dependent on and cant seem to find the issue. Help would be greatly appreciated as I have yet to find a better war plugin for my server.

**Comment by ShermansWorld** [comment]
You need the following plugins installed on your server to run AlathraWar v1.3.1

- TAB plugin [](https://github.com/NEZNAMY/TAB)
- Towny
- Towny SiegeWar
- Vault

Please make sure these plugins are up to date. AlathraWar is designed to run on Minecraft 1.19.x.

Also I'm curious, did you find this github page or have you played on my server AlathraMC?

**Comment by MoneyRBK** [comment]
I am running it on 1.16.5, which is probably why it won't work, and yes I have played alathra before.

**Comment by ShermansWorld** [comment]
Only early versions support 1.16.5, and those contain critical bugs. 1.3.1 for 1.19 is probably best. I have no plans to offer backwards compatibility unless someone submits a pull request.
